title: Natalia Hernandez Berrios
logo: Natalia Hernandez_Headshot_2022.jpg
description: Research & Policy Analyst
#show_downloads: true

theme: just-the-docs

include:
  - assets/css
  
sass:
  sass_dir: assets/css
  
just_the_docs:
  nav_order:
    - Home
    - About
    - Projects
    - Contact
