title: Natalia Hernandez Berrios
description: Research & Policy Analyst
logo: Natalia Hernandez_Headshot_2022.jpg

remote_theme: just-the-docs/just-the-docs

color_scheme: light

# Optional custom CSS
sass:
  sass_dir: _sass

just_the_docs:
  nav_sort: case_sensitive
